[build]
command = "npm run build:css"
functions = "server"
publish = "public"

[functions]
included_files = ["views/*.eta", "data/*.json"]

[dev]
command = "npm run dev:css"
port = 3000

[[redirects]]
from = "/*"
to = "/.netlify/functions/main"
status = 200
